import Head from 'next/head';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Titulo bacana haha</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <h1>A Karininha é muito gatinha!</h1>
      </main>
    </div>
  );
}
